### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by EricControls** [pcdshub/ads-async#34]
Apologies for submitting a false issue as a means to communicate with creators. I'm intrigued about what this tool does. I cloned and installed but can't get it to do 'something'.

Would anyone care to share a bit more info?

this is my output:
`INFO:ads_async.bin.utils:Got PLC net ID through service port: BLOCKED.1.1
ERROR:ads_async.protocol:Deserialization of <class 'ads_async.structs.AoEReadResponse'> failed: Buffer size too small (0 instead of at least 8 bytes) bytes=b'' (length=0); this may be fatal. (Header=AmsTcpHeader(reserved=0, length=32) + AoEHeader(target=BLOCKEDa.1.1:851(R0_PLC_TC3), source=BLOCKED.1.1:851(R0_PLC_TC3), command_id=<AdsCommandId.READ_WRITE: 9>, state_flags=<AoEHeaderFlag.ADS_COMMAND|RESPONSE: 5>, length=0, error_code=18, invoke_id=101))
Traceback (most recent call last):
  File "C:\Users\BLOCKED\AppData\Roaming\Python\Python310\site-packages\ads_async\protocol.py", line 115, in from_wire
    cmd = cmd_cls.deserialize(view)
  File "C:\Users\BLOCKED\AppData\Roaming\Python\Python310\site-packages\ads_async\structs.py", line 175, in deserialize
    new_struct = cls.from_buffer(buf)
ValueError: Buffer size too small (0 instead of at least 8 bytes)
{
    "Global_Variables.bBlink": "(Exception) TimeoutError Response not received in 2.0 seconds"
}`

**Comment by klauer** [comment]
I assume you're running just `ads-async get plc_name_here Global_Variables.bBlink`? I didn't see it in your output.

ADS itself can be a bit finicky. My guess is that the PLC is forcefully closing the connection prior to the request going through.

Here are a couple relevant limitations you might not be aware of:
* The main limitation is that there can't be two TCP connections to the same PLC from the same host. That is to say, if you have TwinCAT XAE talking to your PLC, ads-async won't be able to talk to it effectively. Similarly, you couldn't run two `ads-async monitor` processes in separate terminals on the same host; the PLC would only accept one.
* You need to have a route added to the PLC for the specific machine - otherwise the PLC won't accept your requests. Assuming you already added a route through the IDE, this _shouldn't_ be the problem here. However, ads-async also offers the ability to add a route for you with a few additional command-line arguments (see `ads-async get --help` arguments `--add-route`, `--our-net-id`, and `--our-host`. From a Windows perspective, it may seem unnecessary to require those arguments, but remember that ads-async will run on Linux and macOS as well)

If neither of those applies, then you may have run into a "real" bug (at least something that ads-async could solve on its own). If you could provide even redacted debug log output, it could help resolve it. (`ads-async --log DEBUG get plc_name ...`)

**Comment by EricControls** [comment]
I am working locally on my engineering environment.
`ads-async get localhost Global_Varibles.bBlink`

I will attempt again as soon as I'm around hardware.

Thanks so much for your respond!
